### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by AlexVialaBellander** [czheo/macopilot#1]
Can we add a keyboard shortcut?

like CMD+G or something

**Comment by czheo** [comment]
@AlexVialaBellander Thanks for the feedback. Added to my TODO list. I will look into this when I get a chance.

**Comment by czheo** [comment]
Shortcut `CTRL+G` is added in `v0.1.0` release: https://github.com/czheo/macopilot/releases/tag/v0.1.0
I may plan to make it configurable in later release, if there's a demand.

**Comment by AlexVialaBellander** [comment]
![image](https://github.com/czheo/macopilot/assets/42417723/c91920f7-5db4-428e-a870-0c1075ca0b06)
thx <3
