### ISSUE TITLE
Hide dock icon

### ISSUE THREAD

**Issue by artlambi** [czheo/macopilot#2]
Would be great to have an option to hide the dock icon.

**Comment by czheo** [comment]
@artlambi Thanks for the feedback. I will take a look if that's feasible when I got a chance.

**Comment by artlambi** [comment]
@czheo Awesome, thank you!

**Comment by czheo** [comment]
@artlambi fixed in https://github.com/czheo/macopilot/releases/tag/v0.1.2

**Comment by artlambi** [comment]
@czheo Perfect, thanks again!
